# Generated by Django 3.1.4 on 2020-12-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('PC', 'PC'), ('LAPTOP', 'LAPTOP')], max_length=30)),
                ('purchase_date', models.DateField()),
            ],
        ),
    ]
