# Generated by Django 3.1.4 on 2020-12-23 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee'),
        ),
    ]
