# Generated by Django 3.1.4 on 2020-12-23 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20201223_0815'),
        ('computer', '0003_auto_20201223_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computer', to='employee.employee'),
        ),
    ]
