# Generated by Django 3.1.4 on 2020-12-23 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='room_id',
            new_name='room',
        ),
    ]
