# Generated by Django 3.1.4 on 2020-12-23 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0005_remove_computer_owner'),
        ('employee', '0002_auto_20201223_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='computer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='computer.computer'),
        ),
    ]
